### ISSUE TITLE
Instructions mention non-existent function: gh_store_key

### ISSUE THREAD

**Issue by Robinlovelace** [ropenscilabs/ropsec#36]
Many thanks for a great package!

Just tried it and I was told:

```
The next step is uploading the public key to GitHub or alternative (unless it is already uploaded),  which you can do by passing the return value ("B7C36D5D358D44F0") to `gh_store_key`.
```

Should it point to `store_public_key()`?

``` r
library(ropsec); ls("package:ropsec")
#> [1] "full_on_audit"           "sign_commits_with_key"  
#> [3] "store_public_key"        "summarize_system_checks"
```

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by czeildi** [comment]
thanks, you are right! I'll fix this asap (1-2 days) or you can do a PR if you would like

**Comment by Robinlovelace** [comment]
Great fix, many thanks!
