### ISSUE TITLE
store_public_key function not working?

### ISSUE THREAD

**Issue by Robinlovelace** [ropenscilabs/ropsec#37]
Following on from #36 I tried running this: 

```r
ropsec::store_public_key("B7C36D5D358D4XXX", service = "gh")
#> Error in Sys.getenv(ifelse(service == "gh", "GITHUB_PAT", "GITLAB_PAT"), : wrong type for argument
```

Not sure what this error message means or how to proceed. Thanks!

**Comment by czeildi** [comment]
Thanks! I could reproduce this problem, the problem is that the value of `unset` in `Sys.getenv` must be a character string, cannot be `NULL`.

**Comment by czeildi** [comment]
A possible workaround until this is fixed: pass your GitHub token directly to the `store_public_key` function in the .token argument.

**Comment by Robinlovelace** [comment]
Great fix @czeildi, many thanks, look forward to testing this out, inspired by the rOpenSci community call on this :rocket:
