### ISSUE TITLE
gpg signing to different remotes with different users

### ISSUE THREAD

**Issue by czeildi** [ropenscilabs/ropsec#7]
I use both gitlab and github with different email and would like to sign my commits at both places. Should I have different keys? How to use those? Add support and documentation for this.

**Comment by czeildi** [comment]
I dig around a bit. My understanding is that I definitely need separate gpg keys for separate name - email pairs. I did not find a way to set rules globally like: if git local.user.email is this, use this key, otherwise that.

I think it is fairly common to have 2 emails and you use both regularly it several repositories each: a personal and a work email. I think it would be nice to provide frictionless support for this use case.

I have the following in mind:

* the user should be able to identify the key she wants to use by either the key id or email or name: if the email or name is ambiguous we can still throw an error. Otherwise I always have to search for the key first I want to provide.
* by default set signing key only for current project, not globally. Or maybe have shortcut functions: both use cases seem frequent: if you only have one email you do not want to think about local vs global. otherwise if you have multiple emails it is a bit dangerous to overwrite global git options by default
* for email and username we could check local git config first and if it is not set, fall back to global git config
* generate new key if you do not have one for given name - email pair

I plan to submit a pull request for this but would be great to hear your ideas beforehand @karawoo @hrbrmstr .

**Comment by karawoo** [comment]
I agree we should support both scenarios as seamlessly as possible. I use one email for all git stuff and don't want to set up commit signing on a per-repo basis, but I see why some people would. I think your proposal to check local git config first and then fall back to global makes perfect sense.
